namespace Displasrios.Recaudacion.Core.Constants
{
    public static class CString
    {
        public const string EMAIL_TEMPLATE = "<div style='background-color:#F6EABE;color:#555;width:80%; height:430px; margin:0 auto; border-bottom:5px solid #000;font-family:Arial, Helvetica, sans-serif;'><div style='width:100%;height:170px;background-color:#000;text-align:center'><img src='https://i.imgur.com/jSADthV.png'width='170' height='170'/></div><div style='background-color:#000;height:70px;padding:3px;border-top:1px #fff solid'><h2 style='color:#fff;text-align:center'>Verificación de correo electrónico<h2></div><section style='padding:20px;'><p style='font-size:20px; line-height:1.9rem; text-align:center'>Código de verificación:</p><div style='font-size:22px;border-radius:25px;background-color:#fff;font-weight:bold;text-align:center;width:80%;margin:0 auto;'><p style='padding:5px 5px 15px'>@code</p></div></section> </div>";

        public const string VERIFICACION_CODE_TEMPLATE = "<div style='background-color:#fff;color:#555;width:80%; height:430px; margin:0 auto; border-bottom:5px solid #7538b9;font-family:Arial, Helvetica, sans-serif;'><div style='width:100%;height:170px;background-color:#7538b9;text-align:center'><img src='https://i.imgur.com/1h9VVq1.png'width='250' height='170'/></div><div style='background-color:#212529;height:70px;padding:3px;border-top:1px #fff solid'><h2 style='color:#fff;text-align:center'>Verificación de correo electrónico<h2></div><section style='padding:20px;'><p style='font-size:20px; line-height:1.9rem; text-align:center'>Código de verificación:</p><div style='font-size:22px;border-radius:25px;background-color:#EDEDED;font-weight:bold;text-align:center;width:80%;margin:0 auto;'><p style='padding:5px 5px 15px; color: #7538b9; font-weight: bold;'>@code</p></div></section> </div>";

        public const string RECIBO_TEMPLATE = @"<div style='margin: 0;  box-sizing: border-box;  font-family: arial;  font-size: 13px;  color: rgba(0, 0, 0, 0.7);  height: @heigthWrapper'>  <div style='width: 70%;height: 100%;margin: 0 auto;border: 1px solid rgba(0, 0, 0, 0.2);background-color: #7538b9;'>  <div style='width: 80%;height: 100%;margin: 0 auto;background-color: #7538b9;'>      <header style='background:#f4f4f4; padding:0.5rem; '>		<h5 style='margin:0'>DISPLASRIOS</h5>      </header>    <div style='height: @heigthChild; background-color: #fff; padding: 20px 40px;'>      <div style='text-align:center'>		<h1 style='color:#7538b9;'>RECIBO DE PAGO<br/></h1>	  <p style='margin-bottom:0'>DISTRIBUIDORA DE PLÁSTICOS LOS RIOS</p>	  <p style='margin-top:0.2rem;margin-bottom:0'>RUC: 1202085872001</p>	  <p style='margin-top:0.2rem'>DIR: 9 DE OCTUBRE Y FLORES 504</p>	  </div>	  <div style='width: 100%;height: 1px;background-color: rgba(0, 0, 0, 0.2);margin: auto;'></div>      <div style='font-size: 0.7rem;padding-bottom: 15px;margin-top: 0;'>        <div style='width: 100%;margin: auto;'>			<div style='float:left; width:50%;'>			  <h4>Datos del Cliente:</h4>			  <div style='font-size: 0.6rem; padding-bottom:1rem'>				<p style='margin-bottom:0.2rem'>@nombreCliente</p>				<p style='margin-bottom:0.2rem'>@direccion</p>				<p style='margin-bottom:0'>@email</p>			  </div>			</div>			<div style='float:right; width:50%;'>			  <h4 class='dark'>Nro. Orden: @orderNumber</h4>			  <p><strong>COMPROBANTE Nro:</strong> @numInvoice</p>			  <p>@fechaEmision</p>			</div>		</div>      </div>      <div style='display:block; margin-top:6.5rem;margin-bottom:1rem;  font-size: 0.7rem;width: 100%;'>		@details      </div>      <div  style='font-size: 0.7rem;font-weight: 900;width: 100%;' align=right>        <div style='width: 190px;height: 1px;background-color: rgba(0, 0, 0, 0.2);margin: auto;'></div>        <table style='font-size:12px;text-align:right; margin-top:1rem'>			<tr>				<td><strong>Subtotal:</strong></td>				<td style='text-align:rigth'>$@subtotal</td>			</tr>			<tr>				<td ><strong >Iva:</strong></td>				<td style='text-align:rigth'>$ @eliva</td>			</tr>			<tr>				<td><strong>Descuento:</strong></td>				<td style='text-align:rigth'>$ @descuento</td>			</tr>			<tr>				<td><strong>TOTAL:<strong></td>				<td style='text-align:rigth'>$ @total</td>			</tr>		</table>	 </div>	</div>  </div> </div></div>";
    }
}